version: '3.8'

services:
  backend:
    build:
      context: C:/Programming/NodeJS/exjs
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase

  frontend:
    build:
      context: C:/Programming/VueJS/workshop
    ports:
      - "8080:8080"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: