version: '3.8'
services:
  backend:
    build:
      context: C:/Programming/NodeJS/exjs
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/mydatabase

  frontend:
    build:
      context: C:/Programming/VueJS/workshop
    ports:
      - "8080:8080"